config/routes.rb
Tuflegrad::Application.routes.draw do

  root to: 'application#index'


  namespace :admin do
    resources :articles
    resources :shops
    resources :banners
    resources :vacancies
    resources :comments do
      get :approve, on: :member
    end
    resource :setting
  end

  resources :articles
  resources :vacancies do
    post :reply, on: :member
  end
  resources :comments

end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image, ArticleImageUploader
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  mount_uploader :image, BannerImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  def get_url
  	"http://tg.abardacha.ru/admin/comments/#{id}"
  end
end

app/models/settings.rb
class Settings < ActiveRecord::Base
end

app/models/shop.rb
class Shop < ActiveRecord::Base

  mount_uploader :image, ShopImageUploader
  geocoded_by :full_street_address, lookup: :yandex
  after_validation :geocode

  def full_street_address
    I18n.t 'full_address', {address: address}
  end


end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  def index
    @articles = Article.order('id desc')
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params

    if @article.save
      redirect_to admin_articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find params[:id]
  end

  def update
    @article = Article.find params[:id]

    if @article.update_attributes article_params
      redirect_to admin_articles_path
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find params[:id]
    @article.destroy
    redirect_to :back
  end

  private

  def article_params
    params.require(:article).permit(:title, :image, :annotation, :content)
  end
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < AdminController
  def index
    @banners = Banner.order(:id)
  end

  def new
    @banner = Banner.new
  end

  def create
    @banner = Banner.new banner_params

    if @banner.save
      redirect_to admin_banners_path
    else
      render :new
    end
  end

  def edit
    @banner = Banner.find params[:id]
  end

  def update
    @banner = Banner.find params[:id]

    if @banner.update_attributes banner_params
      redirect_to admin_banners_path
    else
      render :edit
    end
  end

  def destroy
    @banner = Banner.find params[:id]
    @banner.destroy
    redirect_to :back
  end

  private

  def banner_params
    params.require(:banner).permit!
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController
  def index
    @comments = Comment.order('id desc')
  end

  def show
    @comment = Comment.find params[:id]
  end

  def edit
    @comment = Comment.find params[:id]
  end

  def update
    @comment = Comment.find params[:id]
    @comment.update_attributes comment_params
    redirect_to :back
  end

  def approve
    Comment.find(params[:id]).update_attributes(moderated: true)
    redirect_to :back
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit!
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < AdminController
  def edit
    @settings = Settings.first()
  end

  def update
    @settings = Settings.first
    @settings.update_attributes settings_params
    redirect_to edit_admin_setting_path
  end

  private

  def settings_params
    params.require(:settings).permit!
  end
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < AdminController
  def index
    @shops = Shop.order(:id)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new shop_params

    if @shop.save
      redirect_to admin_shops_path
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find params[:id]
  end

  def update
    @shop = Shop.find params[:id]

    if @shop.update_attributes shop_params
      redirect_to admin_shops_path
    else
      render :edit
    end
  end

  def destroy
    @shop = Shop.find params[:id]
    @shop.destroy
    redirect_to :back
  end

  private

  def shop_params
    params.require(:shop).permit!
  end
end

app/controllers/admin/vacancies_controller.rb
class Admin::VacanciesController < AdminController
  def index
    @vacancies = Vacancy.order(:id)
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new vacancy_params

    if @vacancy.save
      redirect_to admin_vacancies_path
    else
      render :new
    end
  end

  def edit
    @vacancy = Vacancy.find params[:id]
  end

  def update
    @vacancy = Vacancy.find params[:id]

    if @vacancy.update_attributes vacancy_params
      redirect_to admin_vacancies_path
    else
      render :edit
    end
  end

  def destroy
    @vacancy = Vacancy.find params[:id]
    @vacancy.destroy
    redirect_to :back
  end

  private

  def vacancy_params
    params.require(:vacancy).permit!
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "privet123"
  protect_from_forgery

  layout 'admin'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @shops = Shop.order(:id)
    @articles = Article.order('id desc').limit(5)
    @settings = Settings.first()
    @banners = Banner.order("id desc")
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order('id desc')
  end

  def show
    @article = Article.find params[:id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.where(moderated: true).order('id desc')
  end

  def create
    @comment = Comment.new comment_params

    if @comment.save


      message = I18n.t(
        'project.new_comment_message',
        url: @comment.get_url,
        locale: 'ru'
      )

      message += "\n"
      message += "http://tg.abardacha.ru/admin/comments"

      Pony.mail ({
          to: 'abardacha@gmail.com, peregubko.e@yandex.ru',
          subject: I18n.t('project.new_comment_title', locale: 'ru'),
          body: message.html_safe,
          via: :smtp,
          via_options: {
              address: 'smtp.gmail.com',
              port: 587,
              enable_starttls_auto: true,
              user_name: 'abardacha@gmail.com',
              password: 'fiolent149',
              authentication: :plain
          }
      })


      render json: {status: :ok}
    else
      render json: {status: :error}
    end
  end

  private

  def comment_params
    params.require(:comment).permit!
  end

end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  def index
    @vacancies = Vacancy.order('id desc')
  end

  def show
    @vacancy = Vacancy.find params[:id]
  end

  def reply
  	@vacancy = Vacancy.find params[:id]

  	message = I18n.t(
  		'project.vacancy_reply_message',
  		name: params[:order][:name],
  		phone: params[:order][:phone],
  		locale: 'ru'
  	)

  	Pony.mail ({
        to: 'abardacha@gmail.com, peregubko.e@yandex.ru',
        subject: I18n.t('project.vacancy_reply_title', vacancy_name: @vacancy.name, locale: 'ru'),
        body: message,
        via: :smtp,
        via_options: {
            address: 'smtp.gmail.com',
            port: 587,
            enable_starttls_auto: true,
            user_name: 'abardacha@gmail.com',
            password: 'fiolent149',
            authentication: :plain
        }
    })
    
    render json: {status: :ok}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_form.html.haml
= simple_form_for article, url: url do |f|
  = f.input :title
  = image_tag article.image_url(:thumb) if article.image?
  = f.input :image
  = f.input :annotation
  = f.input :content, input_html: {id: :edit}
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/articles/edit.html.haml
%legend
  Изменить новость

.row
  .col-md-8
    = render partial: 'admin/articles/form', locals: {article: @article, url: admin_article_path(@article)}

app/views/admin/articles/index.html.haml
%legend
  Новости и акции

  %a.btn{href: new_admin_article_path, style: 'float: right'} Добавить


%table.table.table-striped
  %thead
    %tr
      %td
        Заголовок
      %td
        Дата
      %td
        = '...'

  %tbody
    - @articles.each do |article|
      %tr
        %td
          = article.title
        %td
          = article.created_at

        %td
          = link_to 'редактировать', edit_admin_article_path(article)
          = link_to 'удалить', admin_article_path(article), method: :delete, confirm: 'Удалить статью?'

app/views/admin/articles/new.html.haml
%legend
  Добавить новость

.row
  .col-md-8
    = render partial: 'admin/articles/form', locals: {article: @article, url: admin_articles_path}

app/views/admin/banners/_form.html.haml
= simple_form_for banner, url: url do |f|
  = f.input :name
  = image_tag banner.image_url(:full) if banner.image?
  = f.input :image
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/banners/edit.html.haml
%legend
  Редактировать баннер

.row
  .col-md-12
    = render partial: 'admin/banners/form', locals: {banner: @banner, url: admin_banner_path(@banner)}

app/views/admin/banners/index.html.haml
%legend
  Магазины

  %a.btn{href: new_admin_banner_path, style: 'float: right'} Добавить


%table.table.table-striped
  %thead
    %tr
      %td Название
      %td Дата загрузки
      %td ...


  %tbody
    - @banners.each do |banner|
      %tr
        %td
          = banner.name
        %td
          = banner.created_at.strftime("%d.%m.%Y")

        %td
          = link_to 'редактировать', edit_admin_banner_path(banner)
          = link_to 'удалить', admin_banner_path(banner), method: :delete, confirm: 'Удалить этот баннер?'

app/views/admin/banners/new.html.haml
%legend
  Добавить баннер

.row
  .col-md-12
    = render partial: 'admin/banners/form', locals: {banner: @banner, url: admin_banners_path}

app/views/admin/comments/_form.html.haml
= simple_form_for comment, url: url do |f|
  = f.input :reply
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/comments/index.html.haml
%legend
  Комментарии


%table.table.table-striped
  %thead
    %tr
      %td
        Автор
      %td
        Текст
      %td
        Статус
      %td
        = '...'

  %tbody
    - @comments.each do |comment|
      %tr
        %td
          = comment.name
        %td
          = comment.content
        %td
          - if comment.moderated?
            %span.label.label-success Опубликовано
          - else
            %span.label.label-warning Ожидает модерации
        %td
          - unless comment.moderated?
            = link_to 'Одобрить', approve_admin_comment_path(comment), class: ['btn', 'btn-success']
          = link_to 'Ответить', admin_comment_path(comment), class: ['btn', 'btn-primary']
          = link_to 'Удалить', admin_comment_path(comment), method: :delete, confirm: 'Удалить?', class: ['btn', 'btn-danger']

app/views/admin/comments/show.html.haml
%legend
  Комментарий

.jumbotron
  %p
    = @comment.content

  = render partial: 'admin/comments/form', locals: {comment: @comment, url: admin_comment_path(@comment)}

app/views/admin/settings/edit.html.haml
%legend
  Настройки

.row
  .col-md-6

    = simple_form_for @settings, url: admin_setting_path(@settings) do |f|
      = f.input :about_company, input_html: {rows: 20}
      = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/shops/_form.html.haml
= simple_form_for shop, url: url do |f|
  = f.input :name
  = image_tag shop.image_url(:thumb) if shop.image?
  = f.input :image
  = f.input :phone
  = f.input :address
  = f.input :schedule_weekdays
  = f.input :schedule_weekend
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/shops/edit.html.haml
%legend
  Редактировать магазин

.row
  .col-md-6
    = render partial: 'admin/shops/form', locals: {shop: @shop, url: admin_shop_path(@shop)}

app/views/admin/shops/index.html.haml
%legend
  Магазины

  %a.btn{href: new_admin_shop_path, style: 'float: right'} Добавить


%table.table.table-striped
  %thead
    %tr
      %td Название
      %td Телефон
      %td Адрес
      %td
        = '...'

  %tbody
    - @shops.each do |shop|
      %tr
        %td
          = shop.name
        %td
          = shop.phone
        %td
          = shop.address

        %td
          = link_to 'редактировать', edit_admin_shop_path(shop)
          = link_to 'удалить', admin_shop_path(shop), method: :delete, confirm: 'Удалить магазин?'

app/views/admin/shops/new.html.haml
%legend
  Добавить магазин

.row
  .col-md-6
    = render partial: 'admin/shops/form', locals: {shop: @shop, url: admin_shops_path}

app/views/admin/vacancies/_form.html.haml
= simple_form_for vacancy, url: url do |f|
  = f.input :name
  = f.input :salary_min
  = f.input :salary_max
  = f.input :experience
  = f.input :schedule
  = f.input :description
  = f.input :phone
  = f.input :email
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/vacancies/edit.html.haml
%legend
  Изменить вакансию

.row
  .col-md-6
    = render partial: 'admin/vacancies/form', locals: {vacancy: @vacancy, url: admin_vacancy_path(@vacancy)}

app/views/admin/vacancies/index.html.haml
%legend
  Вакансии

  %a.btn{href: new_admin_vacancy_path, style: 'float: right'} Добавить


%table.table.table-striped
  %thead
    %tr
      %td Название
      %td
        = '...'

  %tbody
    - @vacancies.each do |vacancy|
      %tr
        %td
          = vacancy.name

        %td
          = link_to 'редактировать', edit_admin_vacancy_path(vacancy)
          = link_to 'удалить', admin_vacancy_path(vacancy), method: :delete, confirm: 'Удалить магазин?'

app/views/admin/vacancies/new.html.haml
%legend
  Добавить вакансию

.row
  .col-md-6
    = render partial: 'admin/vacancies/form', locals: {vacancy: @vacancy, url: admin_vacancies_path}

app/views/application/_shops.html.haml
.shops.clearfix
  - shops.each do |shop|
    .shop{lat: shop.latitude, lng: shop.longitude, name: shop.name}
      .img
        = image_tag shop.image_url(:thumb)

      .contacts

        .name
          = shop.name

        .contact-name Телефон:
        .phone
          = shop.phone

        .contact-name Адрес:
        .address
          = shop.address

        .contact-name Режим работы:
        .schedule
          В будни:
          = shop.schedule_weekdays
          %br
          В выходные:
          = shop.schedule_weekend

app/views/application/index.html.haml
.slider
  %ul.bxslider
    - @banners.each do |banner|
      %li
        = image_tag banner.image_url(:full)


.title
  О сети магазинов обуви «Туфлеград»


.main-page.clearfix
  .content

    .text
      %p
        = @settings.about_company.gsub("\n", "<br />").html_safe

  .news-block
    .articles-column
      = render partial: 'articles/list', locals: {articles: @articles}



.title.shops-title#shops
  Адреса и телефоны магазинов


= render partial: 'application/shops', locals: {shops: @shops}


#map

app/views/articles/_list.html.haml
- articles.each do |article|
  .article.clearfix
    = image_tag article.image_url(:mini)
    %span.date
      = article.created_at.strftime('%d.%m.%Y')
    = link_to article.title, articles_path(anchor: "article-#{article.id.to_s}")

app/views/articles/index.html.haml
.title Новости и акции

.articles
  - @articles.each do |article|
    .article.clearfix{id: "article-#{article.id.to_s}"}

      = image_tag article.image_url(:thumb), float: :left
      %h1
        = article.title
        %small
          = article.created_at.strftime('%d.%m.%Y')

      = article.content.html_safe



      -# .top.clearfix
        .image
          = image_tag article.image_url(:thumb)
        .right
          -#.date
            = article.created_at.strftime('%d.%m.%Y')
          .title
            = article.title
            -#= link_to article.title, article_path(article)

      -#  .content
          = article.content.html_safe

        -#= link_to 'Читать далее', article_path(article), class: 'read-more'

app/views/articles/show.html.haml
.breadcrumbs
  = link_to 'Новости и акции', articles_path
  = ' / '
  = @article.title

.title{style: 'margin-top: 0px; height: auto; margin-bottom: 20px'}
  = @article.title


.text
  %p
    = @article.content.html_safe

app/views/comments/index.html.haml
.modal-overlay
.modal
  .name Спасибо за отзыв
  .content
    Ваш отзыв появится на сайте сразу после прохождения модерации.


.title Книга отзывов и предложений

.comments-block.clearfix
  .comments

    - @comments.each do |comment|
      .comment
        .name
          = comment.name
          %span.date
            = comment.created_at.strftime('%d.%m.%Y')

        .content
          = comment.content.gsub("\n", "<br />").html_safe

          - if comment.reply?
            .reply
              .admin Ответ администрации
              = comment.reply



  .right
    .form-block
      .form-offer
        Нам очень важно знать ваше мнение!


      .form
        %input{type: :text, name: :name, placeholder: 'Введите ваше имя'}
        %textarea{name: :content, placholder: 'Напишите ваш отзыв тут'}
        .button.submit-comment Отправить отзыв

app/views/layouts/_admin_topbar.html.haml
%nav.navbar.navbar-default{role: :navigation}
  .container
    .navbar-header
      %button.navbar-toggle{type: :button, 'data-toggle' => 'collapse'}
        %span.sr-only
          Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: admin_articles_path}
        ADMIN

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: params[:controller] == 'admin/articles' ? 'active' : ''}
          %a{href: admin_articles_path}
            Новости

        %li{class: params[:controller] == 'admin/banners' ? 'active' : ''}
          %a{href: admin_banners_path}
            Баннеры

        %li{class: params[:controller] == 'admin/shops' ? 'active' : ''}
          %a{href: admin_shops_path}
            Магазины


        %li{class: params[:controller] == 'admin/vacancies' ? 'active' : ''}
          %a{href: admin_vacancies_path}
            Вакансии

        %li{class: params[:controller] == 'admin/settings' ? 'active' : ''}
          %a{href: edit_admin_setting_path}
            Настройки

        %li{class: params[:controller] == 'admin/comments' ? 'active' : ''}
          %a{href: admin_comments_path}
            Комментарии

app/views/layouts/_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter37955520 = new Ya.Metrika({
                    id:37955520,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/37955520" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/_topbar.html.haml
.topbar.clearfix
  .logo
    %a{href: root_path}
      = image_tag 'logo.png'

  .ok
    %a{href: 'http://www.odnoklassniki.ru/group/52035652419737', target: '_blank'}
      = image_tag 'ok.png'

  .vk
    %a{href: 'http://vk.com/public78083745', target: '_blank'}
      = image_tag 'vk.png'

  %a.adresses-and-phones.show-shops{href: '/#shops'}
    Адреса и телефоны магазинов



.navbar
  %ul.nav
    %li
      = link_to 'Главная страница', root_path

    %li
      = link_to 'Новости и акции', articles_path

    %li
      = link_to 'Вакансии', vacancies_path

    %li
      = link_to 'Отзывы', comments_path

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'admin', :media => 'all'
    = javascript_include_tag 'admin'


    %title
      Панель управления

  %body
    = render partial: 'layouts/admin_topbar'

    .container

      -#%ol.breadcrumb
      -#  = render_breadcrumbs separator: ' / ', class: :li

      = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    %meta{name: :description, content: 'Магазин обуви и сумок Туфлеград'}
    %meta{name: :keywords, content: "обувь ухта, магазин обуви ухта, обувной магазин ухта, купить обувь ухта, сумки ухта, туфлеград, ухта, обувь, сумки, ухта, детская обувь ухта"}
    %meta{name: 'yandex-verification', content: '488476c60f004499'}
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'http://api-maps.yandex.ru/2.1/?lang=ru_RU'
    = javascript_include_tag 'application'


    -#= set_meta_tags site: 'My Site'
    %title
      Туфлеград

  %body
    .wrapper
      = render partial: 'layouts/topbar'
      = yield
      #footer
        .line
        .footer-content
          ООО «Туфлеград»
          %br
          2003 - 2014
          %br
          Все права защищены

    = render partial: 'layouts/metrika'